#!/usr/bin/env python3
#
# This file is part of powerd.
#
# powerd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# powerd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with powerd.  If not, see <http://www.gnu.org/licenses/>.

"""Commandline client for the dome light"""

import datetime
import json
import os
import sys
import Pyro4

PYRO_HOST = '192.168.0.102'
PYRO_PORT = 9009
PYRO_NAME = 'power_daemon'
PYRO_COMM_TIMEOUT = 5

PYRO_URI = 'PYRO:' + PYRO_NAME + '@' + PYRO_HOST + ':' + str(PYRO_PORT)
SCRIPT_NAME = os.path.basename(sys.argv[0])

if __name__ == '__main__':
    if len(sys.argv) > 1 and (sys.argv[1] == 'on' or sys.argv[1] == 'off'):
        enable = sys.argv[1] == 'on'
        Pyro4.config.COMMTIMEOUT = PYRO_COMM_TIMEOUT
        with Pyro4.Proxy(PYRO_URI) as power:
            if not power.switch('light', enable):
                print('error: failed to switch light {}'.format(sys.argv[1]))
                sys.exit(-1)
            sys.exit(0)

    print('usage: {} (on|off)'.format(SCRIPT_NAME))
    sys.exit(-1)

