#!/usr/bin/env python3
#
# This file is part of the Robotic Observatory Control Kit (rockit)
#
# rockit is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rockit is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rockit.  If not, see <http://www.gnu.org/licenses/>.

"""Frontend for interacting with the PDUs and UPSes via SNMP."""

import argparse
import datetime
import sys
import Pyro4
from rockit.common import log
from rockit.common.helpers import pyro_client_matches
from rockit.power import Config, SwitchStatus, SwitchableParameter

# Include more detailed exceptions
sys.excepthook = Pyro4.util.excepthook


class PowerDaemon:
    """Wraps a web request to the PDUs and UPSes"""
    def __init__(self, config):
        self._devices = config.get_devices()
        self._control_ips = config.control_ips
        self._log_name = config.log_name
        self._labels = config.get_labels()

        self._dashboard_ip = config.dashboard_ip
        self._dashboard_toggleable_parameters = config.dashboard_toggleable_parameters

        # Map of parameter name to device holding the parameter
        self._device_by_parameter = {}
        self._parameters_by_name = {}
        for device in self._devices:
            for parameter in device.parameters:
                self._device_by_parameter.update({parameter.name: device})
                self._parameters_by_name.update({parameter.name: parameter})

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement"""
        data = {'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}
        for device in self._devices:
            data.update(device.status())
        return data

    @Pyro4.expose
    def measurement_labels(self):
        """Query the labels associated with last_measurement"""
        return self._labels

    @Pyro4.expose
    def switch_names(self):
        """Queries the list of the switchable parameters"""
        return [k for k, v in self._parameters_by_name.items() if isinstance(v, SwitchableParameter)]

    def switch_internal(self, name, enable):
        """Switch a named switch parameter on or off
           Used internally (avoids the pyro client checks)
        """
        if name not in self._device_by_parameter:
            return False

        if not isinstance(self._parameters_by_name[name], SwitchableParameter):
            return False

        state = (SwitchStatus.On if enable else SwitchStatus.Off)
        ret = self._device_by_parameter[name].set_parameter(name, state)
        if ret:
            log.info(self._log_name, 'Switched ' + name + (' on' if enable else ' off'))
        else:
            log.error(self._log_name, 'Failed to switch ' + name + (' on' if enable else ' off'))
        return ret

    @Pyro4.expose
    def switch(self, name, enable):
        """Switch a named switch parameter on or off"""
        if not pyro_client_matches(self._control_ips):
            return False

        return self.switch_internal(name, enable)

    @Pyro4.expose
    def value(self, name):
        """Query the value of a named parameter"""
        if name not in self._device_by_parameter:
            return False

        return self._device_by_parameter[name].get_parameter(name)

    @Pyro4.expose
    def dashboard_switch(self, name, enable, dashboard_username):
        """Switch a named switch parameter on or off from the web dashboard"""
        if not pyro_client_matches([self._dashboard_ip]):
            return False

        if name not in self._dashboard_toggleable_parameters:
            return False

        log.info(self._log_name, dashboard_username + ' switching ' + name + ' from web dashboard')
        return self.switch_internal(name, enable)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Power Server')
    parser.add_argument('config', help='Path to configuration json file')
    args = parser.parse_args()
    c = Config(args.config)
    c.daemon.launch(PowerDaemon(c))
